# Generated by Django 4.0 on 2022-01-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('title', models.CharField(max_length=254)),
                ('body', models.TextField()),
            ],
        ),
    ]
